import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import { Navbar } from '@/components/home/navbar/navbar'
import { numericFont, primaryFont } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'آکادمی فوتبال سپاهان مسجدسلیمان',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
        className={`relative ${primaryFont.className} ${numericFont.className} adad min-h-screen antialiased `}
      >
        <Navbar className="top-6" />

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
